### ISSUE TITLE
The link of [checkpoint] are broken.

### ISSUE THREAD

**Issue by 402650294** [cybercore-co-ltd/track2_aicity_2021#8]
Hi, I want to download the checkpoint, but the google link are broken.
Could you update link? Thanks.

1. Comparison with state-of-the art methods on VeRi776
Download the [checkpoint](https://drive.google.com/file/d/1iOwk054Fs2pbqnOTQ0UJSv7Yhhk7IRun/view?usp=sharing)

**Comment by ra4-z** [comment]
Same question. I think the title of "A strong baseline for vehicle Re-ID" needs a weights file.

**Comment by chuong98** [comment]
very sorry, we also lost the checkpoints, when we update our hard drive. 
We could not find the google link neither, since it was uploaded using personal google drive.
